# Generated by Django 5.2.16 on 2026-08-02 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_jadval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Janri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janr_nomi', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kitoblar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=15)),
                ('avtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_jadval.avtor')),
                ('janr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog_jadval.janri')),
            ],
        ),
    ]
