# Generated by Django 5.2.16 on 2026-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_jadval', '0002_janri_kitoblar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avtor',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
