# Generated by Django 5.2.16 on 2026-08-02 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_jadval', '0003_avtor_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=100)),
                ('matni', models.TextField()),
                ('chop_etish_sana', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratish_sana', models.DateTimeField(auto_now_add=True)),
                ('ozgarish_sana', models.DateTimeField(auto_now=True)),
                ('avtor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_jadval.avtor')),
            ],
        ),
    ]
