# Generated by Django 5.2.16 on 2026-08-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_jadval', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slag',
            field=models.SlugField(default=True, max_length=255, null=True),
        ),
    ]
