# Generated by Django 5.2.16 on 2026-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_jadval', '0005_post_slag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slag',
            field=models.SlugField(blank=True, default=True, max_length=255, null=True),
        ),
    ]
